version: 2.1


jobs:
  build:
    docker:
      - image: cypress/browsers:latest
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run e2e
          command: npm run test
          no_output_timeout: 180m


      - run:
          name: Generate mocha report
          command: npm run mochawesome:merge
          when: always

      - store_artifacts:
          name: Report uploading
          path: mochawesome-report/
          destination: reports/
      - store_artifacts:
          name: Videos uploading
          path: cypress/videos/
          destination: videos/
      - store_artifacts:
          name: Screenshots uploading
          path: cypress/screenshots/
          destination: screenshots/

workflows:
  version: 2

  commit:
    jobs:
      - build

  nightly_run:
    triggers:
      - schedule:
          cron: "30 3 * * *"
          filters:
            branch:
              only:
                - master
